### ISSUE TITLE
Introducing a keystore-like format

### ISSUE THREAD

**Issue by 0xjjpa** [privy-io/shamir-secret-sharing#14]
# What

I'm suggesting the introduction of a [keystore](https://goethereumbook.org/keystore/)-like format that can be used to provide meaningful metadata to the share generated, instead of the plain Buffer-like representation. In the same way that a traditional crypto private key benefits from being stored into a keystore, a secret share would benefit of metadata describing the data that it's trying to protect without disclosing the actual data.

# Why

Although one can argue that the lack of metadata for the secret to encrypt is a feature and not a bug, the storage, operation and usage of blobs of shares can become cumbersome after some time. In short, `080198161f3f4aa4cc91d5a16d7cdf47db3cb3b1b8640457fa3892701a65b665307c` gives you little to no information which can later be used for rotation or maintenance.

From an operational point of view, looking to these sort of strings in isolation will always required an additional piece of information (e.g. a relational table) to be able to piece together the purpose of the secret the share protects. Losing the relational data can be tricky, specially in the context of digital assets, where compliance to AML/KYC laws might require the removal of shares used as backups for restricted individuals.

In other words, if a crypto address is blacklisted by OFAC (or other similar organisations), and a share related to the respective private key controlling this address, it could be argued that the retainer of these backups could be sanctioned by simply storing this share. By adding metadata, we can guarantee plausible deniability and implement checks in place to trigger automatic systems whenever accounts are flagged.

# How

I suggest the following schema to be used for the generation of the shares, which could be then integrated during the generation of the shares as an additional parameter. The result would be a JSON-like string, that would have the adequate information.

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sharestore",
  "type": "object",
  "properties": {
    "total": {
      "type": "number",
      "description": "The total number of shares."
    },
    "threshold": {
      "type": "number",
      "description": "The minimum number of shares required to reconstruct the secret."
    },
    "instance": {
      "type": "number",
      "description": "The instance number associated with this share store."
    },
    "encrypted": {
      "type": "boolean",
      "description": "A flag indicating whether the shares are encrypted."
    },
    "share_sha512": {
      "type": "string",
      "description": "The SHA-512 hash of the share data."
    },
    "secret_sha512": {
      "type": "string",
      "description": "The SHA-512 hash of the original secret."
    }
  },
  "required": ["total", "threshold", "instance", "encrypted", "share_sha512", "secret_sha512"]
}
```

Given the current interface, we could see the following updated requirements:

```typescript
const [share1, share2, share3] = await split(Buffer.from("secret key"), 3, 2, "sharestore");
console.log(share1)
> {
  total: 3,
  threshold: 2,
  instance: 0,
  encrypted: false,
  share_sha512: "60a74011c9c137da5313e9d1841b55e15e92dceb7ae290ea956718c07506278e4c074e9deed541306d013930dcf8dc721d5483ee65df626e5bbf95759ad91494",
  secret_sha512: "5010c61629c8f7ba65fad18ecb2db472d093d7c820503ac2c238eced7dfcd9414a0f31868f672e85f2032421d7cb3ad7cf8ea604659f39f64dc77981df1ac75a"
}
```

(where `share_sha512` is the SHA-512 value of the hexadecimal representation of the share as a Buffer, and `secret_sha512` is the SHA-512 value of the string-like value of the original secret. These could be adapted to also be the hexadecimal representation, but in the example, `secret_sha512` is the SHA-512 value of the string "secret key")

For encryption, we could pass an array of strings to `bcrypt` or `pbkdf2` for encryption, or a `CryptoKey` with `encrypt` capabilities (e.g. `AES-GCM`), as follows:

```typescript
const [encryptedShare1, share2, share3] = await split(Buffer.from("secret key"), 3, 2, "sharestore", ["password", null, null]);
```

which would flag the content of `encrypted` to `true`, but not of `share_sha512`.

# Additional notes

I'm sure within Privy there's some internal processes to decorate the user's shares with enough information, as well as to Key-Encrypt-Key (KEK) the backup share to avoid falling into custodianship of the related digital assets. However, I'm looking to define a standard for storing Shamir Secret share's, to handle the use cases described in the "Why" section. These topics are real concerns in the institutional digital asset ecosystem and a standard like this would heavily benefit the industry. Sadly, I was unable to pin point the origin of the Keystore format, and thus, thought as the current most up-to-date and open-source implementation, this would be the right place.

It's important to mention the current metadata does not solve the issue related to OFAC-sanctioned addresses, as no meaningful information is still included related to crypto. First, I would like to keep these generic, and in a separate step, include an additional flag targeting crypto, perhaps an attribute like `account_sha512` which could then be used to verify on sanctioned lists.

As a final note, I'm also looking to have these sort of format to be consumable via physical format, as described in the following diagram:

![Paper Blockchain 52](https://github.com/privy-io/shamir-secret-sharing/assets/1128312/12c1f650-97de-4693-9d85-10d81a2300b3)

*(I've isolated the checksum data of the shares in case these would want to be stripped for security reasons within any organisation. However, ideally, the QR code would have everything needed, and a tool would suffice to scan and restore them if gathered all in a single place)*

Please kindly discuss. If there's enough interest to implement this, I would happily help with the creation of the PR to implement the feature.

**Comment by benjreinhart** [comment]
Hey @0xjjpa, thank you for this detailed proposal and context! I do not speak for the folks at Privy, but I'll add my 2c.

### My TLDR

There is some value to this extra metadata, but I'm not convinced the best solution is to augment the existing interface and/or add it as part of this library.

### Longer

> looking to these sort of strings in isolation will always required an additional piece of information (e.g. a relational table) to be able to piece together the purpose of the secret the share protects.

This is likely to always be true, even if this implementation decorates the shares with some extra metadata. In the example you gave regarding a sanctioned list, that refers to one specific usage of this general purpose algorithm (shares relating to a private key of an address on some blockchain network). As you later pointed out, this interface should not be coupled to a particular domain, and so users (e.g., Privy) would still need to store additional metadata in order to make proper use of the shares.

I do agree that standardization is great. But if every use case of this library requires different metadata, then how much value does standardizing the subset of info that is generic add? Maybe a lot, but it's hard to know for sure without a large number of real world examples. (As of the time I worked with Privy, we didn't use all of the metadata in this proposal).

All that said, my biggest source of hesitation is not the metadata itself but the specific implementation proposed here. For an implementation of nuanced and sensitive code (e.g., cryptography), there is a lot of value to keeping that implementation as minimal as possible. In addition to any future maintenance, it makes auditing the code easier both for professionals or the average dev, which in turn provides confidence in the implementation. Even though this proposal adds relatively straightforward behavior/code, it nevertheless would complicate the interface and its implementation. I would personally bias towards leaving this as is until it becomes clear through lots of real-world usage that the extra code+behavior is justified (which means a non-trivial amount of community usage).

If this was to be added, I see a couple options:

1. Expand the existing interface.
2. Wrap this library with custom application code (or perhaps a new library).
3. Have this library export two separate interfaces: The lower-level interface which is free of any metadata (what exists today) and the higher-level interface which wraps the lower-level one with the metadata.

This proposal argues for 1). In the short term, I argue for 2). Longer term, assuming this library is popular and folks share these problems, then I argue for 3). If we we're to do 3), one option is to do so as part of a major release and change the default exported interface to include the metadata, while keeping a subpath export that is just the lower-level interface. In either case, the implementation of 3) should keep the existing code and metadata wrapping separate for maintainability / auditing purposes.

### Final notes

> First, I would like to keep these generic, and in a separate step, include an additional flag targeting crypto, perhaps an attribute like account_sha512 which could then be used to verify on sanctioned lists.

To be clear, I don't think this library should ever include domain-specific attributes. IMO, it should remain a generic cryptography library.

> I'm also looking to have these sort of format to be consumable via physical format

That looks super cool, and I believe it's something Privy was also interested in when I was there. However, similarly to the above, IMO it belongs outside of this library.
